import './keyboard/keyboard.js'
import './objectInfo/objectInfo.js'
import './toolbar/toolbar.js'
import './objectMenu/objectMenu.js'
import './createObjectMenu/createObjectMenu.js'
import './animationPreview/animationPreview.js'
import './hud/hud.js'